### PR TITLE
Customizable schema from configuration

### PR DESCRIPTION
**Pull request by ionlizarazu**
- Add volto default schema functionality to the sidebar
- Make Form and Field schema customizable from configuration
- Add to the fieldSchema properties the possibility to send extra information to the backend
- Send all extra defined information of each field parameter to the backend on submit

### CODE REVIEW

**Review by Arhell — APPROVED** [review]

**Comment by giuliaghisini** [comment]
> * Add volto default schema functionality to the sidebar
> * Make Form and Field schema customizable from configuration
> * Add to the fieldSchema properties the possibility to send extra information to the backend
> * Send all extra defined information of each field parameter to the backend on submit

i'll take a look as soon as possible! it's a big work!

**Comment by tiberiuichim** [comment]
@ionlizarazu Awesome! Big +1 from me

**Comment by ionlizarazu** [comment]
@giuliaghisini 
- Why shoud we send all the properties from the fieldSchema to the backend? [FormView.jsx#L74](https://github.com/collective/volto-form-block/blob/395cb87521d05410ac02984a8761e195b93518ad/src/components/FormView.jsx#L74)
- Label property is setted twice. Once from schema and the second here: [FormView.jsx#L138](https://github.com/collective/volto-form-block/blob/395cb87521d05410ac02984a8761e195b93518ad/src/components/FormView.jsx#L138) I've setted the label field the send_to_backend property to send it by default in this product. Is customizable from schema if someone doesn't need it.

**Comment by giuliaghisini** [comment]
> @giuliaghisini
> 
> * Why shoud we send all the properties from the fieldSchema to the backend? [FormView.jsx#L74](https://github.com/collective/volto-form-block/blob/395cb87521d05410ac02984a8761e195b93518ad/src/components/FormView.jsx#L74)
> * Label property is setted twice. Once from schema and the second here: [FormView.jsx#L138](https://github.com/collective/volto-form-block/blob/395cb87521d05410ac02984a8761e195b93518ad/src/components/FormView.jsx#L138) I've setted the label field the send_to_backend property to send it by default in this product. Is customizable from schema if someone doesn't need it.

because the purpose of this addon is create forms that users can fill in to contact site administrator/editor/company ecc. 
By default, when editor add a field, wants send it to the backend. No send it to the backend could be a configurable possibility.
Label was not sent to the backend, so i've had to add it

**Comment by ionlizarazu** [comment]
> > @giuliaghisini
> > 
> > * Why shoud we send all the properties from the fieldSchema to the backend? [FormView.jsx#L74](https://github.com/collective/volto-form-block/blob/395cb87521d05410ac02984a8761e195b93518ad/src/components/FormView.jsx#L74)
> > * Label property is setted twice. Once from schema and the second here: [FormView.jsx#L138](https://github.com/collective/volto-form-block/blob/395cb87521d05410ac02984a8761e195b93518ad/src/components/FormView.jsx#L138) I've setted the label field the send_to_backend property to send it by default in this product. Is customizable from schema if someone doesn't need it.
> 
> because the purpose of this addon is create forms that users can fill in to contact site administrator/editor/company ecc. By default, when editor add a field, wants send it to the backend. No send it to the backend could be a configurable possibility. Label was not sent to the backend, so i've had to add it


By default all the created fields "value", "field_id" and "label" is sent. What we are choosing when we add the send_to_backend property is the field from the fieldSchema, such as "description", "field_type", "required" or any new parameter for field that the developer wants to add [fieldSchema.js#L130](https://github.com/collective/volto-form-block/blob/395cb87521d05410ac02984a8761e195b93518ad/src/fieldSchema.js#L130)

Here a gif trying to explain the functionality of this original PR
form-sending-test

the @submit-form action will send the following JSON
```
{
  "block_id":"85077506-ba58-402f-acb3-e5d0bd75ad1b",
  "data":[
    {"field_id":"1642492430059","label":"Name","value":"Ion"},
    {"field_id":"1642492478843","label":"Surname","value":"Lizarazu"}, 
    {"field_id":"1642492486115","label":"Email","value":"ilizarazu@testing.com"}, 
    {"field_id":"1642492499979","label":"Message","value":"My message body"}
  ],
  "attachments":{}
}
```

**Review by giuliaghisini — APPROVED** [review]

**Pull request merged**
