### PR TITLE
Add a field_custom_id to identify the field in the backend if needed

### PR DESCRIPTION
**Pull request by libargutxi**
I opened an issue about this changes #13

### CODE REVIEW

**Comment by nzambello** [comment]
@libargutxi I think this would be nonsense to most editors.
I'm wondering if it would be better to have a `field_id` field so it's populated automatically as it's now but advanced editors can also change it as in your use case. Maybe without populating the field if it's the automatic default one.
And then, the description may report it as something advanced and if a user doesn't understand that it's ok and can leave that empty.

**Review by nzambello — COMMENTED** [review]
As I wrote in the issue, I'm not sure we don't have any way to get that field in the backend.
I asked @cekk because he knows this better (he's the backend guy).
I'd like to leave the UI as simple as possible.

**Comment by libargutxi** [comment]
I have no extra data about the fields and I don't know which is the field I need to get the information. There is a field_id for each field you create in the form, but that unique id doesn't allow me to know if it's the field I want to get. For instance, if I want to get the email field information how can I get it?

**Comment by erral** [comment]
Not required anymore after https://github.com/collective/volto-form-block/pull/18

**Pull request closed without merging**
